/* DO NOT EDIT THIS FILE ! */
/* This file has been generated by the pipeline*/

import { DesignToken } from '@microsoft/fast-foundation';

const { create } = DesignToken;

export const fpsfaThemeBgDefault = create<string>('fpsfaThemeBgDefault');
export const fpsfaThemeBgSubtle = create<string>('fpsfaThemeBgSubtle');
export const fpsfaThemeBgMuted = create<string>('fpsfaThemeBgMuted');
export const fpsfaThemeFgDefault = create<string>('fpsfaThemeFgDefault');
export const fpsfaThemeFgOnAccent = create<string>('fpsfaThemeFgOnAccent');
export const fpsfaThemeFgMuted = create<string>('fpsfaThemeFgMuted');
export const fpsfaThemeFgSubtle = create<string>('fpsfaThemeFgSubtle');
export const fpsfaThemeAccentDefault = create<string>('fpsfaThemeAccentDefault');
export const fpsfaThemeAccentSubtle = create<string>('fpsfaThemeAccentSubtle');
export const fpsfaColorsBlack = create<string>('fpsfaColorsBlack');
export const fpsfaColorsWhite = create<string>('fpsfaColorsWhite');
export const fpsfaColorsRed50 = create<string>('fpsfaColorsRed50');
export const fpsfaColorsRed100 = create<string>('fpsfaColorsRed100');
export const fpsfaColorsRed200 = create<string>('fpsfaColorsRed200');
export const fpsfaColorsRed300 = create<string>('fpsfaColorsRed300');
export const fpsfaColorsRed400 = create<string>('fpsfaColorsRed400');
export const fpsfaColorsRed500 = create<string>('fpsfaColorsRed500');
export const fpsfaColorsRed600 = create<string>('fpsfaColorsRed600');
export const fpsfaColorsRed700 = create<string>('fpsfaColorsRed700');
export const fpsfaColorsRed800 = create<string>('fpsfaColorsRed800');
export const fpsfaColorsRed900 = create<string>('fpsfaColorsRed900');
export const fpsfaColorsRed950 = create<string>('fpsfaColorsRed950');
export const fpsfaColorsBlue50 = create<string>('fpsfaColorsBlue50');
export const fpsfaColorsBlue100 = create<string>('fpsfaColorsBlue100');
export const fpsfaColorsBlue200 = create<string>('fpsfaColorsBlue200');
export const fpsfaColorsBlue300 = create<string>('fpsfaColorsBlue300');
export const fpsfaColorsBlue400 = create<string>('fpsfaColorsBlue400');
export const fpsfaColorsBlue500 = create<string>('fpsfaColorsBlue500');
export const fpsfaColorsBlue600 = create<string>('fpsfaColorsBlue600');
export const fpsfaColorsBlue700 = create<string>('fpsfaColorsBlue700');
export const fpsfaColorsBlue800 = create<string>('fpsfaColorsBlue800');
export const fpsfaColorsBlue900 = create<string>('fpsfaColorsBlue900');
export const fpsfaColorsBlue950 = create<string>('fpsfaColorsBlue950');
export const fpsfaColorsGrey50 = create<string>('fpsfaColorsGrey50');
export const fpsfaColorsGrey100 = create<string>('fpsfaColorsGrey100');
export const fpsfaColorsGrey200 = create<string>('fpsfaColorsGrey200');
export const fpsfaColorsGrey300 = create<string>('fpsfaColorsGrey300');
export const fpsfaColorsGrey400 = create<string>('fpsfaColorsGrey400');
export const fpsfaColorsGrey500 = create<string>('fpsfaColorsGrey500');
export const fpsfaColorsGrey600 = create<string>('fpsfaColorsGrey600');
export const fpsfaColorsGrey700 = create<string>('fpsfaColorsGrey700');
export const fpsfaColorsGrey800 = create<string>('fpsfaColorsGrey800');
export const fpsfaColorsGrey900 = create<string>('fpsfaColorsGrey900');
export const fpsfaColorsGrey950 = create<string>('fpsfaColorsGrey950');
